### ISSUE TITLE
Add Process page

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-planninglabs.nyc#13]
Planninglabs.nyc needs a visualization of Labs' project pipeline process. This could additionally link to idea submission.

Steps: 
 - [ ] Design (@andycochran)
 - [ ] Review (@chriswhong)
 - [ ] Implement (@andycochran / @allthesignals ?)
 - [ ] Deploy to staging (@allthesignals)
 - [ ] Deploy to production (@allthesignals)

**Comment by chriswhong** [comment]
Done
