### ISSUE TITLE
Projects page shows current projects, link to ideas

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-planninglabs.nyc#2]

**Comment by andycochran** [comment]
This is addressed in PR https://github.com/NYCPlanning/labs-planninglabs.nyc/pull/3. 

A couple outstanding Qs: 
- What types of images should be used for upcoming projects? We won't have screenshots like we will for complete projects. For the Community Portal, I've used a screenshot of the old portal. But we won't always have something old to snap. 
- Do current/future projects even need images? Perhaps their cards can have a completely different layout with title, GitHub link, idea link, other meta. This will further distinguish the from completed projects visually.
