### ISSUE TITLE
Consider setting the repo website to planninglabs.nyc

### ISSUE THREAD

**Issue by toolness** [NYCPlanning/labs-planninglabs.nyc#6]
It took me a while to realize from the repo name that the website was at planninglabs.nyc.  It might be helpful to set the website for this repo to it, so that folks who stumble upon this repo have an easier time of seeing the live site.

For reference, this is how it shows up on 18F's repo:

> ![2017-06-20_8-15-30](https://user-images.githubusercontent.com/124687/27332672-d11d7306-5590-11e7-8153-6be13df33369.png)

**Comment by chriswhong** [comment]
Done!  Thanks for the reminder.
