### ISSUE TITLE
Where did jenniferthibault's issue on this site's color accessibility go?

### ISSUE THREAD

**Issue by toolness** [NYCPlanning/labs-planninglabs.nyc#6]
Hi!

Back around June 12, @jenniferthibault posted an incredibly well-crafted GitHub issue to this repository about the accessibility of planninglabs.nyc's color palette. It explained why the current palette isn't very accessible, and steps that could be taken to make it more accessible. It had at least one picture in it, as well as a number of hyperlinks that loaded the site's color palette into online color accessibility tools.

Recently I wanted to point it out as a canonical example of a really well-written GitHub issue, but it seems to have disappeared--it hasn't been marked as closed, it's just *gone* entirely. Any idea what happened, or where that issue went?

**Comment by chriswhong** [comment]
Hello!  That issue is now here: https://github.com/NYCPlanning/labs-planninglabs.nyc-archive/issues/5

Once we got a full team on board, we did an overhaul of the site and moved the original one to `labs-planninglabs.nyc-archive`.  We still hope to address the accessibility of the color pallette.

**Comment by allthesignals** [comment]
@toolness also, just to add, @andycochran has done some work on finding an appropriate contrasting orange (similar to "DCP orange" branding), and we're using that in our newest projects.

**Comment by toolness** [comment]
Oh awesome!! Thanks, so glad the issue still exists--and that you're working to fix it too, of course!
